[tool.isort]
profile = "black"
src_paths = ["garmin_uploader", "tests"]

atomic = true
include_trailing_comma = true
use_parentheses = true
line_length = 120

default_section='FIRSTPARTY'
known_first_party = []
known_third_party = [
    'pytest',
    'requests',
    'setuptools',
    'six',
]


[tool.black]
line-length = 120
target-version = [
    'py27',
    'py35',
    'py36',
    'py37',
    'py38',
]
